namespace SnapData.Migrations;

public sealed class PostgresMigrationCompiler : RelationalMigrationCompiler
{
    protected override string ProviderName => "PostgreSQL";

    protected override string IdentityClause => "GENERATED BY DEFAULT AS IDENTITY";

    protected override string QuoteIdentifier(string identifier)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(identifier);
        return $"\"{identifier.Replace("\"", "\"\"", StringComparison.Ordinal)}\"";
    }

    protected override string StoreType(ColumnDefinition column) => column.Type switch
    {
        MigrationColumnType.Int16 => "SMALLINT",
        MigrationColumnType.Int32 => "INTEGER",
        MigrationColumnType.Int64 => "BIGINT",
        MigrationColumnType.String => $"VARCHAR({column.Length ?? 255})",
        MigrationColumnType.Text => "TEXT",
        MigrationColumnType.Boolean => "BOOLEAN",
        MigrationColumnType.Decimal => $"NUMERIC({column.Precision ?? 18},{column.Scale ?? 2})",
        MigrationColumnType.Float => "REAL",
        MigrationColumnType.Double => "DOUBLE PRECISION",
        MigrationColumnType.Guid => "UUID",
        MigrationColumnType.Binary => "BYTEA",
        MigrationColumnType.Date => "DATE",
        MigrationColumnType.Time => "TIME",
        MigrationColumnType.DateTime => "TIMESTAMP",
        MigrationColumnType.DateTimeOffset => "TIMESTAMPTZ",
        MigrationColumnType.Json => "JSONB",
        _ => throw new ArgumentOutOfRangeException(nameof(column.Type), column.Type, null)
    };

    protected override string BooleanLiteral(bool value) => value ? "TRUE" : "FALSE";

    protected override string BinaryLiteral(byte[] value) =>
        $"decode('{Convert.ToHexString(value)}', 'hex')";
}
