namespace SnapData.Migrations;

public sealed class PostgresMigrationCompiler : RelationalMigrationCompiler
{
    protected override string ProviderName => "PostgreSQL";

    protected override string IdentityClause => "GENERATED BY DEFAULT AS IDENTITY";

    protected override string QuoteIdentifier(string identifier)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(identifier);
        return $"\"{identifier.Replace("\"", "\"\"", StringComparison.Ordinal)}\"";
    }

    protected override string StoreType(ColumnDefinition column) => column.Type switch
    {
        MigrationColumnType.Int16 => "SMALLINT",
        MigrationColumnType.Int32 => "INTEGER",
        MigrationColumnType.Int64 => "BIGINT",
        MigrationColumnType.String => $"VARCHAR({column.Length ?? 255})",
        MigrationColumnType.Text => "TEXT",
        MigrationColumnType.Boolean => "BOOLEAN",
        MigrationColumnType.Decimal => $"NUMERIC({column.Precision ?? 18},{column.Scale ?? 2})",
        MigrationColumnType.Float => "REAL",
        MigrationColumnType.Double => "DOUBLE PRECISION",
        MigrationColumnType.Guid => "UUID",
        MigrationColumnType.Binary => "BYTEA",
        MigrationColumnType.Date => "DATE",
        MigrationColumnType.Time => "TIME",
        MigrationColumnType.DateTime => "TIMESTAMP",
        MigrationColumnType.DateTimeOffset => "TIMESTAMPTZ",
        MigrationColumnType.Json => "JSONB",
        _ => throw new ArgumentOutOfRangeException(nameof(column.Type), column.Type, null)
    };

    protected override string BooleanLiteral(bool value) => value ? "TRUE" : "FALSE";

    protected override string BinaryLiteral(byte[] value) =>
        $"decode('{Convert.ToHexString(value)}', 'hex')";

    protected override IEnumerable<string> CompileAlterColumn(AlterColumnOperation operation)
    {
        EnsureAlterColumnHasNoConstraintChanges(operation.Column);
        var table = QuoteTable(operation.Table);
        var column = QuoteIdentifier(operation.Column.Name);
        yield return $"ALTER TABLE {table} ALTER COLUMN {column} TYPE {StoreType(operation.Column)}";
        yield return $"ALTER TABLE {table} ALTER COLUMN {column} " +
            (operation.Column.IsNullable ? "DROP NOT NULL" : "SET NOT NULL");
    }

    protected override string CompileDropIndex(DropIndexOperation operation)
    {
        var parts = operation.Table.Split('.', StringSplitOptions.TrimEntries);
        var index = parts.Length == 2
            ? $"{QuoteIdentifier(parts[0])}.{QuoteIdentifier(operation.Index)}"
            : QuoteIdentifier(operation.Index);
        return $"DROP INDEX {index}";
    }

    protected override IEnumerable<string> CompileCreateTableIfNotExists(
        CreateTableOperation operation,
        string createTableSql,
        IReadOnlyList<string> indexSql)
    {
        yield return createTableSql.Replace(
            "CREATE TABLE ",
            "CREATE TABLE IF NOT EXISTS ",
            StringComparison.Ordinal);
        foreach (var index in operation.Indexes)
        {
            var name = index.Name ?? DefaultIndexName(operation.Table, index);
            var columns = string.Join(", ", index.Columns.Select(column =>
                $"{QuoteIdentifier(column.Name)} {(column.Order == MigrationSortOrder.Descending ? "DESC" : "ASC")}"));
            yield return $"CREATE {(index.IsUnique ? "UNIQUE " : string.Empty)}INDEX IF NOT EXISTS {QuoteIdentifier(name)} ON {QuoteTable(operation.Table)} ({columns})";
        }
    }
}
