using System.Text;

namespace SnapData.Migrations;

public sealed class FirebirdMigrationCompiler : RelationalMigrationCompiler
{
    protected override string ProviderName => "Firebird";

    protected override string IdentityClause => "GENERATED BY DEFAULT AS IDENTITY";

    protected override string QuoteIdentifier(string identifier)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(identifier);
        return $"\"{identifier.Replace("\"", "\"\"", StringComparison.Ordinal)}\"";
    }

    protected override string StoreType(ColumnDefinition column) => column.Type switch
    {
        MigrationColumnType.Int16 => "SMALLINT",
        MigrationColumnType.Int32 => "INTEGER",
        MigrationColumnType.Int64 => "BIGINT",
        MigrationColumnType.String => $"VARCHAR({column.Length ?? 255})",
        MigrationColumnType.Text or MigrationColumnType.Json => "BLOB SUB_TYPE TEXT",
        MigrationColumnType.Boolean => "BOOLEAN",
        MigrationColumnType.Decimal => $"DECIMAL({column.Precision ?? 18},{column.Scale ?? 2})",
        MigrationColumnType.Float => "FLOAT",
        MigrationColumnType.Double => "DOUBLE PRECISION",
        MigrationColumnType.Guid => "CHAR(36)",
        MigrationColumnType.Binary => "BLOB",
        MigrationColumnType.Date => "DATE",
        MigrationColumnType.Time => "TIME",
        MigrationColumnType.DateTime => "TIMESTAMP",
        MigrationColumnType.DateTimeOffset => "TIMESTAMP WITH TIME ZONE",
        _ => throw new ArgumentOutOfRangeException(nameof(column.Type), column.Type, null)
    };

    protected override string BooleanLiteral(bool value) => value ? "TRUE" : "FALSE";

    protected override string BinaryLiteral(byte[] value) => $"X'{Convert.ToHexString(value)}'";

    protected override string CompileColumn(ColumnDefinition column)
    {
        var sql = new StringBuilder()
            .Append(QuoteIdentifier(column.Name)).Append(' ').Append(StoreType(column));
        if (column.IsIdentity)
        {
            sql.Append(' ').Append(IdentityClause);
        }
        if (column.DefaultValue is not null)
        {
            sql.Append(" DEFAULT ").Append(FormatDefault(column.DefaultValue));
        }
        if (!column.IsNullable)
        {
            sql.Append(" NOT NULL");
        }
        if (column.IsUnique)
        {
            sql.Append(" UNIQUE");
        }
        return sql.ToString();
    }

    protected override string QuoteTable(string table)
    {
        if (table.Contains('.', StringComparison.Ordinal))
        {
            throw new NotSupportedException(
                "Firebird schema-qualified table names are not supported.");
        }
        return base.QuoteTable(table);
    }

    protected override string CompileDropColumn(DropColumnOperation operation) =>
        $"ALTER TABLE {QuoteTable(operation.Table)} DROP {QuoteIdentifier(operation.Column)}";

    protected override string CompileRenameColumn(RenameColumnOperation operation) =>
        $"ALTER TABLE {QuoteTable(operation.Table)} ALTER COLUMN {QuoteIdentifier(operation.Column)} TO {QuoteIdentifier(operation.NewName)}";

    protected override string CompileIndex(string table, IndexDefinition index)
    {
        var hasAscending = index.Columns.Any(column =>
            column.Order == MigrationSortOrder.Ascending);
        var hasDescending = index.Columns.Any(column =>
            column.Order == MigrationSortOrder.Descending);
        if (hasAscending && hasDescending)
        {
            throw new NotSupportedException(
                "Firebird indexes cannot mix ascending and descending columns.");
        }

        var name = index.Name ??
            $"{(index.IsUnique ? "UX" : "IX")}_{table.Split('.').Last()}_{string.Join("_", index.Columns.Select(column => column.Name))}";
        var direction = hasDescending ? "DESCENDING " : string.Empty;
        var columns = string.Join(", ", index.Columns.Select(column => QuoteIdentifier(column.Name)));
        return $"CREATE {(index.IsUnique ? "UNIQUE " : string.Empty)}{direction}INDEX {QuoteIdentifier(name)} ON {QuoteTable(table)} ({columns})";
    }
}
