using SnapData.Migrations;
using SnapData.Schema;

namespace SnapData.Migrations.Tests;

public sealed class ProviderMigrationCompilerTests
{
    public static TheoryData<IMigrationCompiler, string, string, string[]> CreateTableCases => new()
    {
        {
            new SqlServerMigrationCompiler(),
            "app.users",
            "app.accounts",
            ["CREATE TABLE [app].[users]", "[id] BIGINT IDENTITY(1,1) NOT NULL", "[name] NVARCHAR(120)", "DEFAULT 1", "REFERENCES [app].[accounts]", "CREATE INDEX [IX_users_name]"]
        },
        {
            new PostgresMigrationCompiler(),
            "app.users",
            "app.accounts",
            ["CREATE TABLE \"app\".\"users\"", "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL", "\"name\" VARCHAR(120)", "DEFAULT TRUE", "REFERENCES \"app\".\"accounts\"", "CREATE INDEX \"IX_users_name\""]
        },
        {
            new MySqlMigrationCompiler(),
            "app.users",
            "app.accounts",
            ["CREATE TABLE `app`.`users`", "`id` BIGINT AUTO_INCREMENT NOT NULL", "`name` VARCHAR(120)", "DEFAULT TRUE", "REFERENCES `app`.`accounts`", "CREATE INDEX `IX_users_name`"]
        },
        {
            new FirebirdMigrationCompiler(),
            "users",
            "accounts",
            ["CREATE TABLE \"users\"", "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL", "\"name\" VARCHAR(120)", "DEFAULT TRUE", "REFERENCES \"accounts\"", "CREATE INDEX \"IX_users_name\""]
        }
    };

    [Theory]
    [MemberData(nameof(CreateTableCases))]
    public void Compilers_generate_provider_specific_create_tables(
        IMigrationCompiler compiler,
        string table,
        string referencedTable,
        string[] expectedFragments)
    {
        var script = compiler.Compile(
            "001", MigrationDirection.Up, CreatePlan(table, referencedTable));

        Assert.Equal(2, script.Statements.Count);
        var rendered = script.ToString();
        foreach (var fragment in expectedFragments)
        {
            Assert.Contains(fragment, rendered);
        }
    }

    [Fact]
    public void Provider_specific_alter_syntax_is_preserved()
    {
        var plan = new MigrationPlan();
        plan.RenameColumn("app.users", "old_name", "new_name");
        plan.DropColumn("app.users", "obsolete");

        Assert.Equal(
            [
                "EXEC sp_rename N'[app].[users].[old_name]', N'new_name', N'COLUMN'",
                "ALTER TABLE [app].[users] DROP COLUMN [obsolete]"
            ],
            new SqlServerMigrationCompiler().Compile("001", MigrationDirection.Up, plan)
                .Statements.Select(statement => statement.Sql));
        var firebirdPlan = new MigrationPlan();
        firebirdPlan.RenameColumn("users", "old_name", "new_name");
        firebirdPlan.DropColumn("users", "obsolete");
        Assert.Equal(
            [
                "ALTER TABLE \"users\" ALTER COLUMN \"old_name\" TO \"new_name\"",
                "ALTER TABLE \"users\" DROP \"obsolete\""
            ],
            new FirebirdMigrationCompiler().Compile("001", MigrationDirection.Up, firebirdPlan)
                .Statements.Select(statement => statement.Sql));
    }

    [Fact]
    public void Firebird_rejects_mixed_index_directions()
    {
        var plan = new MigrationPlan();
        using (var table = plan.CreateTable("events"))
        {
            table.Int64("tenant_id");
            table.DateTime("created_at");
            table.Index("IX_events", "tenant_id", IndexColumn.Desc("created_at"));
        }

        Assert.Throws<NotSupportedException>(() =>
            new FirebirdMigrationCompiler().Compile("001", MigrationDirection.Up, plan));
    }

    [Fact]
    public void Dialects_generate_provider_specific_history_ddl()
    {
        Assert.Contains("[migration_id] NVARCHAR(250)",
            SqlServerMigrationDialect.Instance.CreateHistoryTableSql("app.history"));
        Assert.Contains("\"migration_id\" VARCHAR(250)",
            PostgresMigrationDialect.Instance.CreateHistoryTableSql("app.history"));
        Assert.Contains("`migration_id` VARCHAR(250)",
            MySqlMigrationDialect.Instance.CreateHistoryTableSql("app.history"));
        Assert.Contains("\"migration_id\" VARCHAR(250)",
            FirebirdMigrationDialect.Instance.CreateHistoryTableSql("history"));
    }

    private static MigrationPlan CreatePlan(string tableName, string referencedTable)
    {
        var plan = new MigrationPlan();
        using (var table = plan.CreateTable(tableName))
        {
            table.Identity();
            table.String("name", 120).Default("O'Brien");
            table.Boolean("active").Default(true);
            table.Guid("account_id");
            table.ForeignKey(
                "FK_users_accounts", ["account_id"], referencedTable, ["id"],
                onDelete: ReferentialAction.Cascade);
            table.Index("IX_users_name", "name");
        }
        return plan;
    }
}
