using System.Data;
using FirebirdSql.Data.FirebirdClient;
using SnapData.Schema;

namespace SnapData.IntegrationTests;

[Collection("Firebird provider")]
public sealed class FirebirdSchemaInspectorTests
{
    [FirebirdFact]
    public async Task Discovers_objects_and_reads_column_metadata()
    {
        var connectionString = Environment.GetEnvironmentVariable(
            "SNAPDATA_FIREBIRD_CONNECTION")!;
        var prefix = $"SNAP_{Guid.NewGuid():N}"[..18].ToUpperInvariant();
        var usersName = $"{prefix}_USERS";
        var viewName = $"{prefix}_ACTIVE";
        var typesName = $"{prefix}_TYPES";
        var accountsName = $"{prefix}_ACCOUNTS";
        var linksName = $"{prefix}_LINKS";
        var defaultsName = $"{prefix}_DEFAULTS";
        var domainName = $"{prefix}_CODE";
        var quotedName = $"{prefix}_Mixed";
        await using var connection = new FbConnection(connectionString);
        await connection.OpenAsync();

        try
        {
            await ExecuteAsync(
                connection,
                $"CREATE DOMAIN {domainName} AS VARCHAR(24) NOT NULL",
                $"""
                CREATE TABLE {usersName} (
                    ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
                    NAME VARCHAR(100) NOT NULL,
                    AMOUNT DECIMAL(18,2),
                    ACTIVE BOOLEAN DEFAULT TRUE,
                    NORMALIZED_NAME COMPUTED BY (UPPER(NAME)),
                    PRIMARY KEY (ID),
                    CONSTRAINT {prefix}_UQ_NAME UNIQUE (NAME)
                )
                """,
                $"CREATE DESCENDING INDEX {prefix}_IX_AMOUNT ON {usersName} (AMOUNT, NAME)",
                $"CREATE INDEX {prefix}_IX_NORMALIZED ON {usersName} COMPUTED BY (UPPER(NAME))",
                $"""
                CREATE VIEW {viewName} AS
                    SELECT ID, NAME FROM {usersName} WHERE ACTIVE = TRUE
                """,
                $"""
                CREATE TABLE {typesName} (
                    SMALL_VALUE SMALLINT,
                    INT_VALUE INTEGER,
                    BIG_VALUE BIGINT,
                    REAL_VALUE FLOAT,
                    DOUBLE_VALUE DOUBLE PRECISION,
                    EVENT_DATE DATE,
                    EVENT_TIME TIME,
                    CREATED TIMESTAMP,
                    FIXED_TEXT CHAR(12),
                    TEXT_VALUE VARCHAR(40),
                    FIXED_BINARY BINARY(16),
                    PAYLOAD BLOB SUB_TYPE BINARY,
                    NOTES BLOB SUB_TYPE TEXT,
                    MONEY_VALUE NUMERIC(15,3),
                    PRECISE_VALUE NUMERIC(38,4),
                    HUGE_VALUE INT128,
                    DECIMAL_FLOAT DECFLOAT(16),
                    LARGE_DECIMAL_FLOAT DECFLOAT(34),
                    ZONED_TIME TIME WITH TIME ZONE,
                    ZONED_TIMESTAMP TIMESTAMP WITH TIME ZONE,
                    OCTETS_VALUE CHAR(8) CHARACTER SET OCTETS,
                    DOMAIN_VALUE {domainName},
                    INT_VALUES INTEGER[1:4]
                )
                """,
                $"CREATE TABLE \"{quotedName}\" (\"Value\" INTEGER)",
                $"""
                CREATE TABLE {accountsName} (
                    TENANT_ID INTEGER NOT NULL,
                    ID BIGINT NOT NULL,
                    CONSTRAINT {prefix}_PK_ACCOUNTS PRIMARY KEY (TENANT_ID, ID)
                )
                """,
                $"""
                CREATE TABLE {linksName} (
                    TENANT_ID INTEGER,
                    ACCOUNT_ID BIGINT,
                    CONSTRAINT {prefix}_FK_LINKS
                        FOREIGN KEY (TENANT_ID, ACCOUNT_ID)
                        REFERENCES {accountsName} (TENANT_ID, ID)
                        ON UPDATE CASCADE ON DELETE SET NULL
                )
                """,
                $"""
                CREATE TABLE {defaultsName} (
                    TENANT_ID INTEGER DEFAULT 0 NOT NULL,
                    ACCOUNT_ID BIGINT DEFAULT 0 NOT NULL,
                    CONSTRAINT {prefix}_FK_DEFAULTS
                        FOREIGN KEY (TENANT_ID, ACCOUNT_ID)
                        REFERENCES {accountsName} (TENANT_ID, ID)
                        ON UPDATE NO ACTION ON DELETE SET DEFAULT
                )
                """);

            var database = new SnapDatabase(
                FirebirdClientFactory.Instance,
                connectionString,
                FirebirdQueryCompiler.Instance);
            var inspector = new FirebirdSchemaInspector(database);
            var tableName = new SchemaObjectName(usersName);

            Assert.True(await inspector.TableExistsAsync(tableName));
            Assert.True(await inspector.ColumnExistsAsync(tableName, "NAME"));
            Assert.True(await inspector.ColumnExistsAsync(tableName, "name"));
            Assert.False(await inspector.ColumnExistsAsync(tableName, "MISSING"));
            Assert.Null(await inspector.GetTableAsync(
                new SchemaObjectName($"{prefix}_MISSING")));

            var objects = await inspector.GetObjectsAsync();
            Assert.Contains(objects, item =>
                item.Kind == SchemaObjectKind.Table && item.Name.Name == usersName);
            Assert.Contains(objects, item =>
                item.Kind == SchemaObjectKind.View && item.Name.Name == viewName);
            Assert.DoesNotContain(objects, item => item.IsSystemObject);
            var systemObjects = await inspector.GetObjectsAsync(includeSystemObjects: true);
            Assert.Contains(systemObjects, item => item.IsSystemObject);
            await Assert.ThrowsAsync<ArgumentException>(() =>
                inspector.GetObjectsAsync("PUBLIC"));

            var quotedTable = await inspector.GetTableAsync(
                new SchemaObjectName(quotedName));
            Assert.NotNull(quotedTable);
            Assert.Equal("Value", Assert.Single(quotedTable.Columns).Name);

            var table = (await inspector.GetTableAsync(tableName))!;
            var columns = table.Columns.ToDictionary(column => column.Name);
            Assert.Equal("BIGINT", columns["ID"].StoreType);
            Assert.Equal(DbType.Int64, columns["ID"].DbType);
            Assert.Equal(typeof(long), columns["ID"].ClrType);
            Assert.Equal(SchemaGeneratedKind.Identity, columns["ID"].GeneratedKind);
            Assert.True(columns["ID"].IsAutoIncrement);
            Assert.Equal("VARCHAR(100)", columns["NAME"].StoreType);
            Assert.False(columns["NAME"].IsNullable);
            Assert.Equal("DECIMAL(18,2)", columns["AMOUNT"].StoreType);
            Assert.Equal(typeof(bool), columns["ACTIVE"].ClrType);
            Assert.NotNull(columns["ACTIVE"].DefaultExpression);
            Assert.Equal(
                SchemaGeneratedKind.ComputedVirtual,
                columns["NORMALIZED_NAME"].GeneratedKind);
            Assert.NotNull(table.PrimaryKey);
            Assert.Equal(["ID"], table.PrimaryKey.Columns);

            var primaryIndex = Assert.Single(
                table.Indexes,
                index => index.Origin == SchemaIndexOrigin.PrimaryKey);
            Assert.True(primaryIndex.IsUnique);
            Assert.Equal("ID", Assert.Single(primaryIndex.Columns).Name);
            Assert.Equal("BTREE", primaryIndex.Method);
            Assert.True(primaryIndex.IsVisible);

            var uniqueIndex = Assert.Single(
                table.Indexes,
                index => index.Origin == SchemaIndexOrigin.UniqueConstraint);
            Assert.True(uniqueIndex.IsUnique);
            Assert.Equal("NAME", Assert.Single(uniqueIndex.Columns).Name);

            var descendingIndex = Assert.Single(
                table.Indexes,
                index => index.Name == $"{prefix}_IX_AMOUNT");
            Assert.False(descendingIndex.IsUnique);
            Assert.Equal(["AMOUNT", "NAME"], descendingIndex.Columns
                .Select(column => column.Name));
            Assert.All(descendingIndex.Columns, column => Assert.True(column.Descending));
            Assert.Equal([0, 1], descendingIndex.Columns.Select(column => column.Ordinal));
            Assert.Null(descendingIndex.DefinitionSql);

            var expressionIndex = Assert.Single(
                table.Indexes,
                index => index.Name == $"{prefix}_IX_NORMALIZED");
            var expressionColumn = Assert.Single(expressionIndex.Columns);
            Assert.Null(expressionColumn.Name);
            Assert.Contains(
                "UPPER",
                expressionColumn.Expression,
                StringComparison.OrdinalIgnoreCase);

            var accounts = (await inspector.GetTableAsync(
                new SchemaObjectName(accountsName)))!;
            Assert.Equal(
                ["TENANT_ID", "ID"],
                accounts.PrimaryKey!.Columns);

            var links = (await inspector.GetTableAsync(
                new SchemaObjectName(linksName)))!;
            var foreignKey = Assert.Single(links.ForeignKeys);
            Assert.Equal($"{prefix}_FK_LINKS", foreignKey.Name);
            Assert.Equal(["TENANT_ID", "ACCOUNT_ID"], foreignKey.Columns);
            Assert.Equal(accountsName, foreignKey.ReferencedTable.Name);
            Assert.Null(foreignKey.ReferencedTable.Schema);
            Assert.Equal(["TENANT_ID", "ID"], foreignKey.ReferencedColumns);
            Assert.Equal(ReferentialAction.Cascade, foreignKey.OnUpdate);
            Assert.Equal(ReferentialAction.SetNull, foreignKey.OnDelete);

            var defaults = (await inspector.GetTableAsync(
                new SchemaObjectName(defaultsName)))!;
            var defaultForeignKey = Assert.Single(defaults.ForeignKeys);
            Assert.Equal(ReferentialAction.NoAction, defaultForeignKey.OnUpdate);
            Assert.Equal(ReferentialAction.SetDefault, defaultForeignKey.OnDelete);

            var types = (await inspector.GetTableAsync(
                new SchemaObjectName(typesName)))!;
            var typeColumns = types.Columns.ToDictionary(column => column.Name);
            Assert.Equal(typeof(short), typeColumns["SMALL_VALUE"].ClrType);
            Assert.Equal(typeof(int), typeColumns["INT_VALUE"].ClrType);
            Assert.Equal(typeof(long), typeColumns["BIG_VALUE"].ClrType);
            Assert.Equal(typeof(float), typeColumns["REAL_VALUE"].ClrType);
            Assert.Equal(typeof(double), typeColumns["DOUBLE_VALUE"].ClrType);
            Assert.Equal(typeof(DateOnly), typeColumns["EVENT_DATE"].ClrType);
            Assert.Equal(typeof(TimeOnly), typeColumns["EVENT_TIME"].ClrType);
            Assert.Equal(typeof(DateTime), typeColumns["CREATED"].ClrType);
            Assert.Equal(typeof(string), typeColumns["FIXED_TEXT"].ClrType);
            Assert.Equal(typeof(string), typeColumns["TEXT_VALUE"].ClrType);
            Assert.Equal(typeof(byte[]), typeColumns["FIXED_BINARY"].ClrType);
            Assert.Equal(typeof(byte[]), typeColumns["PAYLOAD"].ClrType);
            Assert.Equal(typeof(string), typeColumns["NOTES"].ClrType);
            Assert.Equal(typeof(decimal), typeColumns["MONEY_VALUE"].ClrType);
            Assert.Equal("NUMERIC(15,3)", typeColumns["MONEY_VALUE"].StoreType);
            Assert.Equal("NUMERIC(38,4)", typeColumns["PRECISE_VALUE"].StoreType);
            Assert.Equal(typeof(Int128), typeColumns["HUGE_VALUE"].ClrType);
            Assert.Equal("INT128", typeColumns["HUGE_VALUE"].StoreType);
            Assert.Equal(typeof(object), typeColumns["DECIMAL_FLOAT"].ClrType);
            Assert.Equal(DbType.Object, typeColumns["DECIMAL_FLOAT"].DbType);
            Assert.Equal("DECFLOAT(16)", typeColumns["DECIMAL_FLOAT"].StoreType);
            Assert.Equal("DECFLOAT(34)", typeColumns["LARGE_DECIMAL_FLOAT"].StoreType);
            Assert.Equal(typeof(object), typeColumns["ZONED_TIME"].ClrType);
            Assert.Equal("TIME WITH TIME ZONE", typeColumns["ZONED_TIME"].StoreType);
            Assert.Equal(typeof(object), typeColumns["ZONED_TIMESTAMP"].ClrType);
            Assert.Equal(
                "TIMESTAMP WITH TIME ZONE",
                typeColumns["ZONED_TIMESTAMP"].StoreType);
            Assert.Equal(typeof(byte[]), typeColumns["OCTETS_VALUE"].ClrType);
            Assert.Contains("OCTETS", typeColumns["OCTETS_VALUE"].StoreType);
            Assert.Equal(domainName, typeColumns["DOMAIN_VALUE"].StoreType);
            Assert.Equal(typeof(string), typeColumns["DOMAIN_VALUE"].ClrType);
            Assert.Equal(typeof(Array), typeColumns["INT_VALUES"].ClrType);
            Assert.Equal("INTEGER ARRAY", typeColumns["INT_VALUES"].StoreType);

            var minimal = await inspector.GetTableAsync(
                tableName,
                new SchemaReadOptions
                {
                    IncludeColumns = false,
                    IncludePrimaryKeys = false,
                    IncludeForeignKeys = false,
                    IncludeIndexes = false
                });
            Assert.Empty(minimal!.Columns);
            Assert.Null(minimal.PrimaryKey);
            Assert.Empty(minimal.ForeignKeys);
            Assert.Empty(minimal.Indexes);

            var schema = await inspector.ReadAsync();
            Assert.False(string.IsNullOrWhiteSpace(schema.Name));
            Assert.Contains(schema.Tables, item => item.Name.Name == usersName);
            var view = Assert.Single(schema.Views, item => item.Name.Name == viewName);
            Assert.Equal(2, view.Columns.Count);
            Assert.Contains("SELECT", view.DefinitionSql, StringComparison.OrdinalIgnoreCase);

            var withoutViews = await inspector.ReadAsync(
                new SchemaReadOptions { IncludeViews = false });
            Assert.Empty(withoutViews.Views);

            var withoutDefinitions = await inspector.ReadAsync(
                new SchemaReadOptions { IncludeDefinitionSql = false });
            Assert.Contains(
                withoutDefinitions.Views,
                item => item.Name.Name == viewName && item.DefinitionSql is null);
        }
        finally
        {
            await DropAsync(
                connection,
                $"DROP VIEW {viewName}",
                $"DROP TABLE {defaultsName}",
                $"DROP TABLE {linksName}",
                $"DROP TABLE {accountsName}",
                $"DROP TABLE \"{quotedName}\"",
                $"DROP TABLE {typesName}",
                $"DROP TABLE {usersName}",
                $"DROP DOMAIN {domainName}");
        }
    }

    private static async Task DropAsync(FbConnection connection, params string[] statements)
    {
        foreach (var statement in statements)
        {
            try
            {
                await ExecuteAsync(connection, statement);
            }
            catch (FbException)
            {
                // Setup may fail part-way through; cleanup should preserve that error.
            }
        }
    }

    private static async Task ExecuteAsync(FbConnection connection, params string[] statements)
    {
        foreach (var statement in statements)
        {
            await using var command = connection.CreateCommand();
            command.CommandText = statement;
            await command.ExecuteNonQueryAsync();
        }
    }
}
