using FirebirdSql.Data.FirebirdClient;

namespace SnapData.IntegrationTests;

[Collection("Firebird provider")]
public sealed class FirebirdProviderTests : ProviderContractTests
{
    private const string ConnectionVariable = "SNAPDATA_FIREBIRD_CONNECTION";

    [FirebirdFact]
    public Task Entity_crud() => Entity_crud_and_generated_identity_round_trip();

    [FirebirdFact]
    public Task Borrowed_session_ownership() =>
        Borrowed_session_does_not_dispose_the_connection();

    [FirebirdFact]
    public Task Transactions() => Transaction_commit_and_rollback_are_observed();

    [FirebirdFact]
    public Task Advanced_queries() =>
        Projection_join_grouping_subquery_and_paging_execute();

    [FirebirdFact]
    public Task Common_types() => Common_provider_types_round_trip();

    [FirebirdFact]
    public async Task Selectable_stored_procedure_returns_typed_rows()
    {
        await using var harness = await CreateHarnessAsync();
        await ExecuteAsync(
            (FbConnection)harness.Connection,
            """
            CREATE OR ALTER PROCEDURE SNAP_ECHO (INPUT_VALUE INTEGER)
            RETURNS (OUTPUT_VALUE INTEGER)
            AS
            BEGIN
                OUTPUT_VALUE = INPUT_VALUE + 1;
                SUSPEND;
            END
            """);

        try
        {
            await using var session = await harness.Database.OpenSessionAsync();

            var result = await session.Query(new EchoProcedure { Value = 41 });

            Assert.Equal(42, Assert.Single(result.Items).Value);
        }
        finally
        {
            await ExecuteAsync((FbConnection)harness.Connection, "DROP PROCEDURE SNAP_ECHO");
        }
    }

    protected override async Task<ProviderHarness> CreateHarnessAsync()
    {
        var connectionString = Environment.GetEnvironmentVariable(ConnectionVariable)!;
        var anchor = new FbConnection(connectionString);
        await anchor.OpenAsync();
        await ExecuteAsync(
            anchor,
            """
            RECREATE TABLE contract_users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(200) NOT NULL,
                active BOOLEAN NOT NULL
            )
            """,
            """
            RECREATE TABLE contract_orders (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                total DECIMAL(18,2) NOT NULL
            )
            """,
            """
            RECREATE TABLE contract_values (
                id BINARY(16) PRIMARY KEY,
                instant TIMESTAMP NOT NULL,
                amount DECIMAL(18,2) NOT NULL,
                payload BLOB SUB_TYPE BINARY NOT NULL,
                optional_text VARCHAR(200)
            )
            """);

        var database = new SnapDatabase(
            FirebirdClientFactory.Instance,
            connectionString,
            FirebirdQueryCompiler.Instance);
        return new FirebirdHarness(database, anchor);
    }

    private static async Task ExecuteAsync(FbConnection connection, params string[] statements)
    {
        foreach (var statement in statements)
        {
            await using var command = connection.CreateCommand();
            command.CommandText = statement;
            await command.ExecuteNonQueryAsync();
        }
    }

    [StoredProcedure("SNAP_ECHO")]
    private sealed class EchoProcedure : IStoredProc<Result<EchoRow>>
    {
        [Input("INPUT_VALUE")]
        public int Value { get; init; }
    }

    private sealed record EchoRow([property: Column("OUTPUT_VALUE")] int Value);

    private sealed class FirebirdHarness(
        SnapDatabase database,
        FbConnection anchor) : ProviderHarness(database)
    {
        public override FbConnection Connection => anchor;

        public override async ValueTask DisposeAsync()
        {
            await anchor.DisposeAsync();
        }
    }
}

[CollectionDefinition("Firebird provider", DisableParallelization = true)]
public sealed class FirebirdProviderCollection;

internal sealed class FirebirdFactAttribute : FactAttribute
{
    public FirebirdFactAttribute()
    {
        if (string.IsNullOrWhiteSpace(
            Environment.GetEnvironmentVariable("SNAPDATA_FIREBIRD_CONNECTION")))
        {
            Skip = "Set SNAPDATA_FIREBIRD_CONNECTION to run Firebird integration tests.";
        }
    }
}
