using Npgsql;

namespace SnapData.IntegrationTests;

public sealed class PostgresProviderTests : ProviderContractTests
{
    private const string ConnectionVariable = "SNAPDATA_POSTGRES_CONNECTION";

    [PostgresFact]
    public Task Entity_crud() => Entity_crud_and_generated_identity_round_trip();

    [PostgresFact]
    public Task Borrowed_session_ownership() =>
        Borrowed_session_does_not_dispose_the_connection();

    [PostgresFact]
    public Task Transactions() => Transaction_commit_and_rollback_are_observed();

    [PostgresFact]
    public Task Advanced_queries() =>
        Projection_join_grouping_subquery_and_paging_execute();

    [PostgresFact]
    public Task Common_types() => Common_provider_types_round_trip();

    protected override async Task<ProviderHarness> CreateHarnessAsync()
    {
        var connectionString = Environment.GetEnvironmentVariable(ConnectionVariable)!;
        var anchor = new NpgsqlConnection(connectionString);
        await anchor.OpenAsync();
        await using (var command = anchor.CreateCommand())
        {
            command.CommandText =
                """
                DROP TABLE IF EXISTS contract_orders;
                DROP TABLE IF EXISTS contract_values;
                DROP TABLE IF EXISTS contract_users;

                CREATE TABLE contract_users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(200) NOT NULL,
                    active BOOLEAN NOT NULL
                );
                CREATE TABLE contract_orders (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    total NUMERIC(18,2) NOT NULL
                );
                CREATE TABLE contract_values (
                    id UUID PRIMARY KEY,
                    instant TIMESTAMPTZ NOT NULL,
                    amount NUMERIC(18,2) NOT NULL,
                    payload BYTEA NOT NULL,
                    optional_text VARCHAR(200) NULL
                );
                """;
            await command.ExecuteNonQueryAsync();
        }

        var database = new SnapDatabase(
            NpgsqlFactory.Instance,
            connectionString,
            PostgresQueryCompiler.Instance);
        return new PostgresHarness(database, anchor);
    }

    private sealed class PostgresHarness(
        SnapDatabase database,
        NpgsqlConnection anchor) : ProviderHarness(database)
    {
        public override NpgsqlConnection Connection => anchor;

        public override async ValueTask DisposeAsync()
        {
            try
            {
                await using var command = anchor.CreateCommand();
                command.CommandText =
                    """
                    DROP TABLE IF EXISTS contract_orders;
                    DROP TABLE IF EXISTS contract_values;
                    DROP TABLE IF EXISTS contract_users;
                    """;
                await command.ExecuteNonQueryAsync();
            }
            finally
            {
                await anchor.DisposeAsync();
            }
        }
    }
}

internal sealed class PostgresFactAttribute : FactAttribute
{
    public PostgresFactAttribute()
    {
        if (string.IsNullOrWhiteSpace(
            Environment.GetEnvironmentVariable("SNAPDATA_POSTGRES_CONNECTION")))
        {
            Skip = "Set SNAPDATA_POSTGRES_CONNECTION to run PostgreSQL integration tests.";
        }
    }
}
