using Npgsql;
using SnapData.Schema;

namespace SnapData.IntegrationTests;

public sealed class PostgresSchemaInspectorTests
{
    [PostgresFact]
    public async Task Discovers_objects_and_reads_column_metadata()
    {
        var connectionString = Environment.GetEnvironmentVariable(
            "SNAPDATA_POSTGRES_CONNECTION")!;
        var schemaName = $"snap_schema_{Guid.NewGuid():N}";
        await using var connection = new NpgsqlConnection(connectionString);
        await connection.OpenAsync();

        try
        {
            await ExecuteAsync(
                connection,
                $"""
                CREATE SCHEMA {schemaName};
                CREATE TYPE {schemaName}.mood AS ENUM ('happy', 'sad');
                CREATE DOMAIN {schemaName}.positive_amount AS NUMERIC(10,2)
                    CHECK (VALUE >= 0);
                CREATE TABLE {schemaName}.users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY
                        CONSTRAINT pk_users PRIMARY KEY,
                    legacy_id SERIAL,
                    name VARCHAR(100) NOT NULL,
                    amount NUMERIC(18,2),
                    active BOOLEAN NOT NULL DEFAULT true,
                    normalized_name TEXT GENERATED ALWAYS AS (upper(name)) STORED
                );
                CREATE VIEW {schemaName}.active_users AS
                    SELECT id, name FROM {schemaName}.users WHERE active;
                CREATE MATERIALIZED VIEW {schemaName}.user_totals AS
                    SELECT count(*)::BIGINT AS total FROM {schemaName}.users;
                CREATE TABLE {schemaName}.type_samples (
                    id UUID NOT NULL,
                    created TIMESTAMP(3) NOT NULL,
                    instant TIMESTAMPTZ,
                    event_date DATE,
                    event_time TIME(2),
                    payload BYTEA,
                    tags JSONB,
                    double_value DOUBLE PRECISION,
                    single_value REAL
                );
                CREATE TABLE {schemaName}.advanced_types (
                    domain_value {schemaName}.positive_amount,
                    mood_value {schemaName}.mood,
                    integer_values INTEGER[],
                    text_values TEXT[],
                    uuid_values UUID[],
                    network_value INET,
                    xml_value XML,
                    bits_value VARBIT(8),
                    duration INTERVAL
                );
                CREATE TABLE {schemaName}.accounts (
                    tenant_id INTEGER NOT NULL,
                    id BIGINT NOT NULL,
                    CONSTRAINT pk_accounts PRIMARY KEY (tenant_id, id),
                    CONSTRAINT uq_accounts UNIQUE (id, tenant_id)
                );
                CREATE TABLE {schemaName}.account_links (
                    tenant_id INTEGER,
                    account_id BIGINT,
                    CONSTRAINT fk_account_links_accounts
                        FOREIGN KEY (tenant_id, account_id)
                        REFERENCES {schemaName}.accounts (tenant_id, id)
                        ON UPDATE CASCADE ON DELETE SET NULL
                );
                CREATE TABLE {schemaName}.default_links (
                    tenant_id INTEGER DEFAULT 0,
                    account_id BIGINT DEFAULT 0,
                    CONSTRAINT fk_default_links_accounts
                        FOREIGN KEY (tenant_id, account_id)
                        REFERENCES {schemaName}.accounts (tenant_id, id)
                        ON UPDATE RESTRICT ON DELETE SET DEFAULT
                );
                CREATE TABLE {schemaName}.no_action_links (
                    tenant_id INTEGER,
                    account_id BIGINT,
                    CONSTRAINT fk_no_action_links_accounts
                        FOREIGN KEY (tenant_id, account_id)
                        REFERENCES {schemaName}.accounts (tenant_id, id)
                );
                CREATE UNIQUE INDEX ix_users_name
                    ON {schemaName}.users (name DESC)
                    INCLUDE (active)
                    WHERE amount IS NOT NULL;
                CREATE INDEX ix_users_normalized
                    ON {schemaName}.users ((lower(name)));
                """);

            var database = new SnapDatabase(
                NpgsqlFactory.Instance,
                connectionString,
                PostgresQueryCompiler.Instance);
            var inspector = new PostgresSchemaInspector(database);
            var tableName = new SchemaObjectName("users", schemaName);

            Assert.True(await inspector.TableExistsAsync(tableName));
            Assert.True(await inspector.ColumnExistsAsync(tableName, "name"));
            Assert.False(await inspector.ColumnExistsAsync(tableName, "missing"));
            Assert.Null(await inspector.GetTableAsync(
                new SchemaObjectName("missing", schemaName)));

            var objects = await inspector.GetObjectsAsync(schemaName);
            Assert.Contains(objects, item =>
                item.Kind == SchemaObjectKind.Table && item.Name.Name == "users");
            Assert.Contains(objects, item =>
                item.Kind == SchemaObjectKind.View && item.Name.Name == "active_users");
            Assert.Contains(objects, item =>
                item.Kind == SchemaObjectKind.View && item.Name.Name == "user_totals");

            var table = await inspector.GetTableAsync(tableName);
            Assert.NotNull(table);
            var columns = table.Columns.ToDictionary(column => column.Name);
            Assert.Equal("bigint", columns["id"].StoreType);
            Assert.Equal(System.Data.DbType.Int64, columns["id"].DbType);
            Assert.Equal(typeof(long), columns["id"].ClrType);
            Assert.Equal(SchemaGeneratedKind.Identity, columns["id"].GeneratedKind);
            Assert.True(columns["id"].IsAutoIncrement);
            Assert.Equal(SchemaGeneratedKind.Identity, columns["legacy_id"].GeneratedKind);
            Assert.True(columns["legacy_id"].IsAutoIncrement);
            Assert.Equal("character varying(100)", columns["name"].StoreType);
            Assert.Equal("numeric(18,2)", columns["amount"].StoreType);
            Assert.NotNull(columns["active"].DefaultExpression);
            Assert.Equal(
                SchemaGeneratedKind.ComputedStored,
                columns["normalized_name"].GeneratedKind);
            Assert.Null(table.DefinitionSql);
            Assert.Equal("pk_users", table.PrimaryKey!.Name);
            Assert.Equal(["id"], table.PrimaryKey.Columns);

            var primaryIndex = Assert.Single(
                table.Indexes,
                index => index.Origin == SchemaIndexOrigin.PrimaryKey);
            Assert.True(primaryIndex.IsUnique);
            Assert.Equal("id", Assert.Single(primaryIndex.Columns).Name);

            var filteredIndex = Assert.Single(
                table.Indexes,
                index => index.Name == "ix_users_name");
            Assert.True(filteredIndex.IsUnique);
            Assert.NotNull(filteredIndex.FilterExpression);
            Assert.NotNull(filteredIndex.DefinitionSql);
            Assert.Equal(2, filteredIndex.Columns.Count);
            Assert.Equal("name", filteredIndex.Columns[0].Name);
            Assert.True(filteredIndex.Columns[0].Descending);
            Assert.False(filteredIndex.Columns[0].IsIncluded);
            Assert.Equal("active", filteredIndex.Columns[1].Name);
            Assert.True(filteredIndex.Columns[1].IsIncluded);

            var expressionIndex = Assert.Single(
                table.Indexes,
                index => index.Name == "ix_users_normalized");
            var expression = Assert.Single(expressionIndex.Columns);
            Assert.Null(expression.Name);
            Assert.Contains("lower", expression.Expression, StringComparison.OrdinalIgnoreCase);
            Assert.Contains("name", expression.Expression, StringComparison.OrdinalIgnoreCase);

            var withoutDefinitions = await inspector.GetTableAsync(
                tableName,
                new SchemaReadOptions { IncludeDefinitionSql = false });
            Assert.All(withoutDefinitions!.Indexes, index => Assert.Null(index.DefinitionSql));
            Assert.NotNull(Assert.Single(
                withoutDefinitions.Indexes,
                index => index.Name == "ix_users_name").FilterExpression);

            var accounts = await inspector.GetTableAsync(
                new SchemaObjectName("accounts", schemaName));
            Assert.Equal(["tenant_id", "id"], accounts!.PrimaryKey!.Columns);
            Assert.Contains(
                accounts.Indexes,
                index => index.Origin == SchemaIndexOrigin.UniqueConstraint);

            var links = await inspector.GetTableAsync(
                new SchemaObjectName("account_links", schemaName));
            var foreignKey = Assert.Single(links!.ForeignKeys);
            Assert.Equal("fk_account_links_accounts", foreignKey.Name);
            Assert.Equal(["tenant_id", "account_id"], foreignKey.Columns);
            Assert.Equal(new SchemaObjectName("accounts", schemaName), foreignKey.ReferencedTable);
            Assert.Equal(["tenant_id", "id"], foreignKey.ReferencedColumns);
            Assert.Equal(ReferentialAction.Cascade, foreignKey.OnUpdate);
            Assert.Equal(ReferentialAction.SetNull, foreignKey.OnDelete);

            var defaultLink = await inspector.GetTableAsync(
                new SchemaObjectName("default_links", schemaName));
            var defaultForeignKey = Assert.Single(defaultLink!.ForeignKeys);
            Assert.Equal(ReferentialAction.Restrict, defaultForeignKey.OnUpdate);
            Assert.Equal(ReferentialAction.SetDefault, defaultForeignKey.OnDelete);

            var noActionLink = await inspector.GetTableAsync(
                new SchemaObjectName("no_action_links", schemaName));
            var noActionForeignKey = Assert.Single(noActionLink!.ForeignKeys);
            Assert.Equal(ReferentialAction.NoAction, noActionForeignKey.OnUpdate);
            Assert.Equal(ReferentialAction.NoAction, noActionForeignKey.OnDelete);

            var minimal = await inspector.GetTableAsync(
                tableName,
                new SchemaReadOptions
                {
                    IncludeColumns = false,
                    IncludePrimaryKeys = false,
                    IncludeForeignKeys = false,
                    IncludeIndexes = false,
                    IncludeViews = false,
                    IncludeDefinitionSql = false
                });
            Assert.Empty(minimal!.Columns);
            Assert.Null(minimal.PrimaryKey);
            Assert.Empty(minimal.ForeignKeys);

            var types = (await inspector.GetTableAsync(
                new SchemaObjectName("type_samples", schemaName)))!;
            var typeColumns = types.Columns.ToDictionary(column => column.Name);
            Assert.Equal(typeof(Guid), typeColumns["id"].ClrType);
            Assert.Equal(typeof(DateTime), typeColumns["created"].ClrType);
            Assert.Equal(typeof(DateTime), typeColumns["instant"].ClrType);
            Assert.Equal(typeof(DateOnly), typeColumns["event_date"].ClrType);
            Assert.Equal(typeof(TimeOnly), typeColumns["event_time"].ClrType);
            Assert.Equal(typeof(byte[]), typeColumns["payload"].ClrType);
            Assert.Equal(typeof(string), typeColumns["tags"].ClrType);
            Assert.Equal(typeof(double), typeColumns["double_value"].ClrType);
            Assert.Equal(typeof(float), typeColumns["single_value"].ClrType);

            var advanced = (await inspector.GetTableAsync(
                new SchemaObjectName("advanced_types", schemaName)))!;
            var advancedColumns = advanced.Columns.ToDictionary(column => column.Name);
            Assert.Contains("positive_amount", advancedColumns["domain_value"].StoreType);
            Assert.Equal(System.Data.DbType.Decimal, advancedColumns["domain_value"].DbType);
            Assert.Equal(typeof(decimal), advancedColumns["domain_value"].ClrType);
            Assert.Equal(System.Data.DbType.String, advancedColumns["mood_value"].DbType);
            Assert.Equal(typeof(string), advancedColumns["mood_value"].ClrType);
            Assert.Equal(typeof(int[]), advancedColumns["integer_values"].ClrType);
            Assert.Equal(typeof(string[]), advancedColumns["text_values"].ClrType);
            Assert.Equal(typeof(Guid[]), advancedColumns["uuid_values"].ClrType);
            Assert.Equal(typeof(System.Net.IPAddress), advancedColumns["network_value"].ClrType);
            Assert.Equal(System.Data.DbType.Xml, advancedColumns["xml_value"].DbType);
            Assert.Equal(typeof(System.Collections.BitArray), advancedColumns["bits_value"].ClrType);
            Assert.Equal(typeof(TimeSpan), advancedColumns["duration"].ClrType);

            var schema = await inspector.ReadAsync();
            Assert.Equal(connection.Database, schema.Name);
            Assert.Contains(schema.Tables, item => item.Name == tableName);
            var view = Assert.Single(schema.Views, item =>
                item.Name == new SchemaObjectName("active_users", schemaName));
            Assert.Equal(2, view.Columns.Count);
            Assert.Contains("SELECT", view.DefinitionSql, StringComparison.OrdinalIgnoreCase);
            Assert.Contains(schema.Views, item =>
                item.Name == new SchemaObjectName("user_totals", schemaName)
                && item.DefinitionSql is not null);

            var withoutViews = await inspector.ReadAsync(
                new SchemaReadOptions { IncludeViews = false });
            Assert.Empty(withoutViews.Views);

            var schemaWithoutDefinitions = await inspector.ReadAsync(
                new SchemaReadOptions { IncludeDefinitionSql = false });
            Assert.Contains(
                schemaWithoutDefinitions.Views,
                item => item.Name == new SchemaObjectName("active_users", schemaName)
                    && item.DefinitionSql is null);
        }
        finally
        {
            await ExecuteAsync(connection, $"DROP SCHEMA IF EXISTS {schemaName} CASCADE");
        }
    }

    private static async Task ExecuteAsync(NpgsqlConnection connection, string sql)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        await command.ExecuteNonQueryAsync();
    }
}
